### ISSUE TITLE
[Bug]  2025.6.3 Bug reports

### ISSUE THREAD

**Issue by Ethan591** [JoshuaMulliken/ha-wyzeapi#703]
**Describe the bug**
Multiple warnings for 2025.6.3, thank you for your help!

**To Reproduce**
NA

**Expected behavior**
Normal set up

**System configuration**
System: Home Assistant OS
Core: 2025.5.3
Supervisor: 2025.06.2
Operating System: 15.2
Frontend: 20250516.0
WyzeApi Version: 0.1.22

**home-assistant.log when updated to 2025.06.2**
```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 8:13:52 AM (1 occurrence)
Last logged: 8:13:52 AM

Error setting up entry for wyzeapi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/__init__.py", line 125, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(config_entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```
**Warnings before update**
```
`Logger: homeassistant.helpers.frame
Source: helpers/frame.py:380
First occurred: 8:19:36 AM (9 occurrences)
Last logged: 8:19:38 AM

Detected code that calls async_forward_entry_setup for integration, wyzeapi with title: and entry_id: 16c47ca1c8cbc6dd07376f8e4a475ca1, which is deprecated, await async_forward_entry_setups instead. This will stop working in Home Assistant 2025.6, please report this issue
Detected code that calls async_forward_entry_setup for integration wyzeapi with title: and entry_id: 16c47ca1c8cbc6dd07376f8e4a475ca1, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue

Logger: homeassistant.components.light
Source: helpers/deprecation.py:222
integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 8:19:37 AM (14 occurrences)
Last logged: 8:19:38 AM

SUPPORT_COLOR_TEMP was used from wyzeapi, this is a deprecated constant which will be removed in HA Core 2026.1. Use supported_color_modes instead, please report it to the author of the 'wyzeapi' custom integration
SUPPORT_COLOR was used from wyzeapi, this is a deprecated constant which will be removed in HA Core 2026.1. Use supported_color_modes instead, please report it to the author of the 'wyzeapi' custom integration
COLOR_MODE_ONOFF was used from wyzeapi, this is a deprecated constant which will be removed in HA Core 2026.1. Use ColorMode.ONOFF instead, please report it to the author of the 'wyzeapi' custom integration
SUPPORT_EFFECT was used from wyzeapi, this is a deprecated constant which will be removed in HA Core 2026.1. Use LightEntityFeature.EFFECT instead, please report it to the author of the 'wyzeapi' custom integration
```
